name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & Push Backend Image
      - name: Build and Push Backend
        working-directory: todo-app/backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      # 4. Build & Push Frontend Image
      - name: Build and Push Frontend
        working-directory: todo-app/frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      # 5. FORCE Render Deployment (NEW APPROACH)
      - name: Nuclear Render Deploy
        run: |
          # Backend deploy
          curl -v -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "do_not_clear"}' \
            "https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_SERVICE_ID }}/deploys" || echo "Backend deploy failed but continuing..."
          
          # Frontend deploy
          curl -v -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "do_not_clear"}' \
            "https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_SERVICE_ID }}/deploys" || echo "Frontend deploy failed but continuing..."
