name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & Push Backend Image
      - name: Build and Push Backend
        working-directory: todo-app/backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      # 4. Build & Push Frontend Image
      - name: Build and Push Frontend
        working-directory: todo-app/frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      # 5. Deploy Backend to Render.com
      - name: Deploy Backend to Render
        run: |
          # If you have a deploy hook for the backend:
          curl -X POST ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        # If webhook isn't available, you can add conditional execution:
        continue-on-error: true
      
      # 6. Deploy Frontend to Render.com
      - name: Deploy Frontend to Render
        run: |
          # If you have a deploy hook for the frontend:
          curl -X POST ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
        # If webhook isn't available, you can add conditional execution:
        continue-on-error: true
